# Generated by Django 4.2.5 on 2023-10-01 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_depertment_remove_advisor_course_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advisor',
            old_name='name',
            new_name='aname',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course',
        ),
        migrations.AddField(
            model_name='advisor',
            name='course',
            field=models.ManyToManyField(blank=True, null=True, to='demo.course'),
        ),
        migrations.AddField(
            model_name='advisor',
            name='deperment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.depertment'),
        ),
        migrations.AddField(
            model_name='advisor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(blank=True, null=True, to='demo.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='deperment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.depertment'),
        ),
    ]
